# 開発環境用

version: "3.4"
services:
  db:
    platform: linux/x86_64 # M1チップ対応
    image: mysql:8.0.32
    command: --table-definition-cache=400 --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./config/docker/mysql/conf.d:/etc/mysql/conf.d
      - db:/var/lib/mysql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - TZ=UTC
    ports:
      - "3306:3306"

volumes:
  db:
  bundle_cache:
